import React, { createContext, useContext, useState } from "react";

type Language = "tr" | "en" | "es" | "fr" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    "nav.about": "Hakkında",
    "nav.tokenomics": "Tokenomics",
    "nav.roadmap": "Roadmap",
    "nav.staking": "Staking",
    "nav.buy": "HEMEN AL",
    "hero.solana": "Solana",
    "hero.title": "The Cyber-Sushi Revolution on Solana",
    "hero.subtitle": "TUNAMI, meme kültürünün eğlencesini Solana'nın hızıyla birleştiren yeni nesil bir AI Agent tokenidir. Dalgalara hazır mısın? 🌊",
    "hero.cta1": "HEMEN AL",
    "hero.cta2": "TELEGRAM",
    "hero.cta3": "STAKE & EARN 💸",
    "hero.ca": "CONTRACT ADDRESS (CA)",
    "hero.ca_placeholder": "Yakında açıklanacak...",
    "about.title": "Neden TUNAMI?",
    "about.subtitle": "Sadece bir meme token değil, aynı zamanda teknolojik bir devrim.",
    "about.feature1": "Işık Hızında",
    "about.feature1_desc": "Solana ağının gücüyle saniyeler içinde işlem onayı. Beklemek yok, sadece hız var.",
    "about.feature2": "%100 Güvenli",
    "about.feature2_desc": "Liquidity yakıldı, mint yetkisi iptal edildi. Topluluk odaklı ve tamamen şeffaf.",
    "about.feature3": "AI Destekli",
    "about.feature3_desc": "Geleceğin teknolojisi AI Agent'lar ile entegre, akıllı ve otonom özellikler.",
    "tokenomics.title": "Tokenomics Yapısı",
    "tokenomics.total_supply": "Toplam Arz",
    "tokenomics.tax": "Alış/Satış Vergisi",
    "tokenomics.lp": "LP Kilitli",
    "tokenomics.benefit1": "Alış/Satış Vergisi Yok 🍣",
    "tokenomics.benefit2": "LP Kilitli 🔥",
    "tokenomics.benefit3": "Team Token Yok 🤝",
    "tokenomics.benefit4": "Tamamen Topluluk Odaklı 🌍",
    "roadmap.title": "Yol Haritası",
    "roadmap.subtitle": "Geleceğe doğru emin adımlarla.",
    "roadmap.phase1": "Faz 1",
    "roadmap.phase1_title": "Başlangıç",
    "roadmap.phase1_item1": "Website Lansmanı",
    "roadmap.phase1_item2": "Topluluk Kurulumu",
    "roadmap.phase1_item3": "Marketing Başlangıcı",
    "roadmap.phase1_item4": "Fair Launch",
    "roadmap.phase2": "Faz 2",
    "roadmap.phase2_title": "Büyüme",
    "roadmap.phase2_item1": "CoinGecko Listeleme",
    "roadmap.phase2_item2": "CoinMarketCap Listeleme",
    "roadmap.phase2_item3": "10,000 Holder Hedefi",
    "roadmap.phase2_item4": "CEX Görüşmeleri",
    "roadmap.phase3": "Faz 3",
    "roadmap.phase3_title": "Hakimiyet",
    "roadmap.phase3_item1": "Tier 1 CEX Listeleme",
    "roadmap.phase3_item2": "TUNAMI NFT Koleksiyonu",
    "roadmap.phase3_item3": "AI Agent Entegrasyonu",
    "roadmap.phase3_item4": "Global Marketing",
    "staking.title": "Stake $TUNAMI",
    "staking.subtitle": "Tokenlarını kilitle, Sushi Rewards kazan.",
    "staking.apy": "Güncel APY",
    "staking.tvl": "Toplam Kilitli (TVL)",
    "staking.earned": "Kazanılan Ödül",
    "staking.panel_title": "Staking Paneli",
    "staking.amount": "Miktar",
    "staking.balance": "Bakiye",
    "staking.estimated_yield": "Tahmini Getiri (Yıllık)",
    "staking.lock_time": "Kilit Süresi",
    "staking.stake_btn": "STAKE ET 🍣",
    "staking.unstake_btn": "UNSTAKE ET 💸",
    "staking.how_works": "Nasıl Çalışır?",
    "staking.step1": "1. Cüzdanını Bağla: Solana cüzdanını (Phantom, Solflare) bağlayarak başla.",
    "staking.step2": "2. Stake Et: Elindeki $TUNAMI tokenları havuza kilitle.",
    "staking.step3": "3. Kazan: Her saniye ödül kazanmaya başla.",
    "staking.vip_title": "VIP Havuzlar 🌊",
    "staking.vip_desc": "Çok yakında NFT sahiplerine özel yüksek getirili havuzlar açılacak!",
    "staking.coming_soon": "Çok Yakında",
    "footer.disclaimer": "Yasal Uyarı: Kripto para yatırımları yüksek risk içerir. Lütfen kendi araştırmanızı yapın (DYOR). Bu site yatırım tavsiyesi değildir.",
  },
  en: {
    "nav.about": "About",
    "nav.tokenomics": "Tokenomics",
    "nav.roadmap": "Roadmap",
    "nav.staking": "Staking",
    "nav.buy": "BUY NOW",
    "hero.solana": "Solana",
    "hero.title": "The Cyber-Sushi Revolution on Solana",
    "hero.subtitle": "TUNAMI combines the fun of meme culture with the speed of Solana. A next-generation AI Agent token. Ready for the wave? 🌊",
    "hero.cta1": "BUY NOW",
    "hero.cta2": "TELEGRAM",
    "hero.cta3": "STAKE & EARN 💸",
    "hero.ca": "CONTRACT ADDRESS (CA)",
    "hero.ca_placeholder": "Coming soon...",
    "about.title": "Why TUNAMI?",
    "about.subtitle": "Not just a meme token, but a technological revolution.",
    "about.feature1": "Lightning Fast",
    "about.feature1_desc": "Transaction confirmation in seconds with Solana's power. No waiting, just speed.",
    "about.feature2": "100% Safe",
    "about.feature2_desc": "Liquidity burned, mint authority revoked. Community-driven and fully transparent.",
    "about.feature3": "AI-Powered",
    "about.feature3_desc": "Future technology integrated with AI Agents, smart and autonomous features.",
    "tokenomics.title": "Tokenomics Structure",
    "tokenomics.total_supply": "Total Supply",
    "tokenomics.tax": "Buy/Sell Tax",
    "tokenomics.lp": "LP Locked",
    "tokenomics.benefit1": "No Buy/Sell Tax 🍣",
    "tokenomics.benefit2": "LP Locked 🔥",
    "tokenomics.benefit3": "No Team Tokens 🤝",
    "tokenomics.benefit4": "100% Community-Driven 🌍",
    "roadmap.title": "Roadmap",
    "roadmap.subtitle": "Moving forward with confidence.",
    "roadmap.phase1": "Phase 1",
    "roadmap.phase1_title": "Launch",
    "roadmap.phase1_item1": "Website Launch",
    "roadmap.phase1_item2": "Community Setup",
    "roadmap.phase1_item3": "Marketing Start",
    "roadmap.phase1_item4": "Fair Launch",
    "roadmap.phase2": "Phase 2",
    "roadmap.phase2_title": "Growth",
    "roadmap.phase2_item1": "CoinGecko Listing",
    "roadmap.phase2_item2": "CoinMarketCap Listing",
    "roadmap.phase2_item3": "10,000 Holders Goal",
    "roadmap.phase2_item4": "CEX Discussions",
    "roadmap.phase3": "Phase 3",
    "roadmap.phase3_title": "Dominance",
    "roadmap.phase3_item1": "Tier 1 CEX Listing",
    "roadmap.phase3_item2": "TUNAMI NFT Collection",
    "roadmap.phase3_item3": "AI Agent Integration",
    "roadmap.phase3_item4": "Global Marketing",
    "staking.title": "Stake $TUNAMI",
    "staking.subtitle": "Lock your tokens, earn Sushi Rewards.",
    "staking.apy": "Current APY",
    "staking.tvl": "Total Value Locked (TVL)",
    "staking.earned": "Rewards Earned",
    "staking.panel_title": "Staking Panel",
    "staking.amount": "Amount",
    "staking.balance": "Balance",
    "staking.estimated_yield": "Estimated Yield (Yearly)",
    "staking.lock_time": "Lock Time",
    "staking.stake_btn": "STAKE 🍣",
    "staking.unstake_btn": "UNSTAKE 💸",
    "staking.how_works": "How It Works?",
    "staking.step1": "1. Connect Wallet: Connect your Solana wallet (Phantom, Solflare).",
    "staking.step2": "2. Stake: Lock your $TUNAMI tokens in the pool.",
    "staking.step3": "3. Earn: Start earning rewards every second.",
    "staking.vip_title": "VIP Pools 🌊",
    "staking.vip_desc": "Coming soon: exclusive high-yield pools for NFT holders!",
    "staking.coming_soon": "Coming Soon",
    "footer.disclaimer": "Disclaimer: Crypto investments carry high risk. Please do your own research (DYOR). This site is not investment advice.",
  },
  es: {
    "nav.about": "Acerca de",
    "nav.tokenomics": "Tokenomics",
    "nav.roadmap": "Hoja de Ruta",
    "nav.staking": "Staking",
    "nav.buy": "COMPRAR AHORA",
    "hero.solana": "Solana",
    "hero.title": "La Revolución Cyber-Sushi en Solana",
    "hero.subtitle": "TUNAMI combina la diversión de la cultura meme con la velocidad de Solana. Un token AI Agent de nueva generación. ¿Listo para la ola? 🌊",
    "hero.cta1": "COMPRAR AHORA",
    "hero.cta2": "TELEGRAM",
    "hero.cta3": "STAKE & EARN 💸",
    "hero.ca": "DIRECCIÓN DEL CONTRATO (CA)",
    "hero.ca_placeholder": "Próximamente...",
    "about.title": "¿Por qué TUNAMI?",
    "about.subtitle": "No solo un token meme, sino una revolución tecnológica.",
    "about.feature1": "Ultra Rápido",
    "about.feature1_desc": "Confirmación de transacciones en segundos con el poder de Solana. Sin esperas, solo velocidad.",
    "about.feature2": "%100 Seguro",
    "about.feature2_desc": "Liquidez quemada, autoridad de acuñación revocada. Impulsado por la comunidad y totalmente transparente.",
    "about.feature3": "Impulsado por IA",
    "about.feature3_desc": "Tecnología del futuro integrada con Agentes de IA, características inteligentes y autónomas.",
    "tokenomics.title": "Estructura de Tokenomics",
    "tokenomics.total_supply": "Suministro Total",
    "tokenomics.tax": "Impuesto Compra/Venta",
    "tokenomics.lp": "LP Bloqueado",
    "tokenomics.benefit1": "Sin Impuesto Compra/Venta 🍣",
    "tokenomics.benefit2": "LP Bloqueado 🔥",
    "tokenomics.benefit3": "Sin Tokens de Equipo 🤝",
    "tokenomics.benefit4": "100% Impulsado por Comunidad 🌍",
    "roadmap.title": "Hoja de Ruta",
    "roadmap.subtitle": "Avanzando con confianza.",
    "roadmap.phase1": "Fase 1",
    "roadmap.phase1_title": "Lanzamiento",
    "roadmap.phase1_item1": "Lanzamiento del Sitio Web",
    "roadmap.phase1_item2": "Configuración de Comunidad",
    "roadmap.phase1_item3": "Inicio de Marketing",
    "roadmap.phase1_item4": "Lanzamiento Justo",
    "roadmap.phase2": "Fase 2",
    "roadmap.phase2_title": "Crecimiento",
    "roadmap.phase2_item1": "Listado en CoinGecko",
    "roadmap.phase2_item2": "Listado en CoinMarketCap",
    "roadmap.phase2_item3": "Objetivo de 10,000 Titulares",
    "roadmap.phase2_item4": "Discusiones en CEX",
    "roadmap.phase3": "Fase 3",
    "roadmap.phase3_title": "Dominio",
    "roadmap.phase3_item1": "Listado en CEX Tier 1",
    "roadmap.phase3_item2": "Colección NFT TUNAMI",
    "roadmap.phase3_item3": "Integración de Agentes IA",
    "roadmap.phase3_item4": "Marketing Global",
    "staking.title": "Stake $TUNAMI",
    "staking.subtitle": "Bloquea tus tokens, gana Recompensas Sushi.",
    "staking.apy": "APY Actual",
    "staking.tvl": "Valor Total Bloqueado (TVL)",
    "staking.earned": "Recompensas Ganadas",
    "staking.panel_title": "Panel de Staking",
    "staking.amount": "Cantidad",
    "staking.balance": "Saldo",
    "staking.estimated_yield": "Rendimiento Estimado (Anual)",
    "staking.lock_time": "Tiempo de Bloqueo",
    "staking.stake_btn": "STAKE 🍣",
    "staking.unstake_btn": "UNSTAKE 💸",
    "staking.how_works": "¿Cómo Funciona?",
    "staking.step1": "1. Conecta tu Billetera: Conecta tu billetera Solana (Phantom, Solflare).",
    "staking.step2": "2. Stake: Bloquea tus tokens $TUNAMI en el pool.",
    "staking.step3": "3. Gana: Comienza a ganar recompensas cada segundo.",
    "staking.vip_title": "Pools VIP 🌊",
    "staking.vip_desc": "¡Próximamente: pools de alto rendimiento exclusivos para poseedores de NFT!",
    "staking.coming_soon": "Próximamente",
    "footer.disclaimer": "Descargo de Responsabilidad: Las inversiones en criptomonedas conllevan alto riesgo. Por favor, haz tu propia investigación (DYOR). Este sitio no es asesoramiento de inversión.",
  },
  fr: {
    "nav.about": "À Propos",
    "nav.tokenomics": "Tokenomics",
    "nav.roadmap": "Feuille de Route",
    "nav.staking": "Staking",
    "nav.buy": "ACHETER MAINTENANT",
    "hero.solana": "Solana",
    "hero.title": "La Révolution Cyber-Sushi sur Solana",
    "hero.subtitle": "TUNAMI combine le plaisir de la culture meme avec la vitesse de Solana. Un token AI Agent de nouvelle génération. Prêt pour la vague ? 🌊",
    "hero.cta1": "ACHETER MAINTENANT",
    "hero.cta2": "TELEGRAM",
    "hero.cta3": "STAKE & EARN 💸",
    "hero.ca": "ADRESSE DU CONTRAT (CA)",
    "hero.ca_placeholder": "Bientôt...",
    "about.title": "Pourquoi TUNAMI ?",
    "about.subtitle": "Pas seulement un token meme, mais une révolution technologique.",
    "about.feature1": "Ultra Rapide",
    "about.feature1_desc": "Confirmation des transactions en secondes avec la puissance de Solana. Pas d'attente, juste de la vitesse.",
    "about.feature2": "%100 Sûr",
    "about.feature2_desc": "Liquidité brûlée, autorité de frappe révoquée. Piloté par la communauté et totalement transparent.",
    "about.feature3": "Alimenté par l'IA",
    "about.feature3_desc": "Technologie future intégrée avec des Agents IA, fonctionnalités intelligentes et autonomes.",
    "tokenomics.title": "Structure de Tokenomics",
    "tokenomics.total_supply": "Offre Totale",
    "tokenomics.tax": "Taxe Achat/Vente",
    "tokenomics.lp": "LP Verrouillé",
    "tokenomics.benefit1": "Pas de Taxe Achat/Vente 🍣",
    "tokenomics.benefit2": "LP Verrouillé 🔥",
    "tokenomics.benefit3": "Pas de Tokens d'Équipe 🤝",
    "tokenomics.benefit4": "%100 Piloté par la Communauté 🌍",
    "roadmap.title": "Feuille de Route",
    "roadmap.subtitle": "Avancer avec confiance.",
    "roadmap.phase1": "Phase 1",
    "roadmap.phase1_title": "Lancement",
    "roadmap.phase1_item1": "Lancement du Site Web",
    "roadmap.phase1_item2": "Configuration de la Communauté",
    "roadmap.phase1_item3": "Début du Marketing",
    "roadmap.phase1_item4": "Lancement Équitable",
    "roadmap.phase2": "Phase 2",
    "roadmap.phase2_title": "Croissance",
    "roadmap.phase2_item1": "Listage CoinGecko",
    "roadmap.phase2_item2": "Listage CoinMarketCap",
    "roadmap.phase2_item3": "Objectif 10 000 Détenteurs",
    "roadmap.phase2_item4": "Discussions CEX",
    "roadmap.phase3": "Phase 3",
    "roadmap.phase3_title": "Domination",
    "roadmap.phase3_item1": "Listage CEX Tier 1",
    "roadmap.phase3_item2": "Collection NFT TUNAMI",
    "roadmap.phase3_item3": "Intégration Agent IA",
    "roadmap.phase3_item4": "Marketing Mondial",
    "staking.title": "Stake $TUNAMI",
    "staking.subtitle": "Verrouillez vos tokens, gagnez des Récompenses Sushi.",
    "staking.apy": "APY Actuel",
    "staking.tvl": "Valeur Totale Verrouillée (TVL)",
    "staking.earned": "Récompenses Gagnées",
    "staking.panel_title": "Panneau de Staking",
    "staking.amount": "Montant",
    "staking.balance": "Solde",
    "staking.estimated_yield": "Rendement Estimé (Annuel)",
    "staking.lock_time": "Durée de Verrouillage",
    "staking.stake_btn": "STAKE 🍣",
    "staking.unstake_btn": "UNSTAKE 💸",
    "staking.how_works": "Comment ça marche ?",
    "staking.step1": "1. Connectez votre Portefeuille : Connectez votre portefeuille Solana (Phantom, Solflare).",
    "staking.step2": "2. Stake : Verrouillez vos tokens $TUNAMI dans le pool.",
    "staking.step3": "3. Gagnez : Commencez à gagner des récompenses chaque seconde.",
    "staking.vip_title": "Pools VIP 🌊",
    "staking.vip_desc": "Bientôt : pools à haut rendement exclusifs pour les détenteurs de NFT !",
    "staking.coming_soon": "Bientôt",
    "footer.disclaimer": "Avertissement : Les investissements en crypto-monnaies comportent un risque élevé. Veuillez faire vos propres recherches (DYOR). Ce site n'est pas un conseil en investissement.",
  },
  de: {
    "nav.about": "Über",
    "nav.tokenomics": "Tokenomics",
    "nav.roadmap": "Roadmap",
    "nav.staking": "Staking",
    "nav.buy": "JETZT KAUFEN",
    "hero.solana": "Solana",
    "hero.title": "Die Cyber-Sushi-Revolution auf Solana",
    "hero.subtitle": "TUNAMI kombiniert den Spaß der Meme-Kultur mit der Geschwindigkeit von Solana. Ein Token der nächsten Generation mit KI-Agent. Bereit für die Welle? 🌊",
    "hero.cta1": "JETZT KAUFEN",
    "hero.cta2": "TELEGRAM",
    "hero.cta3": "STAKE & EARN 💸",
    "hero.ca": "VERTRAGSADRESSE (CA)",
    "hero.ca_placeholder": "Bald verfügbar...",
    "about.title": "Warum TUNAMI?",
    "about.subtitle": "Nicht nur ein Meme-Token, sondern eine technologische Revolution.",
    "about.feature1": "Blitzschnell",
    "about.feature1_desc": "Transaktionsbestätigung in Sekunden mit Solanas Kraft. Kein Warten, nur Geschwindigkeit.",
    "about.feature2": "%100 Sicher",
    "about.feature2_desc": "Liquidität verbrannt, Prägungsautorität widerrufen. Gemeinschaftsgesteuert und vollständig transparent.",
    "about.feature3": "KI-gesteuert",
    "about.feature3_desc": "Zukunftstechnologie integriert mit KI-Agenten, intelligente und autonome Funktionen.",
    "tokenomics.title": "Tokenomics-Struktur",
    "tokenomics.total_supply": "Gesamtangebot",
    "tokenomics.tax": "Kauf-/Verkaufssteuer",
    "tokenomics.lp": "LP Gesperrt",
    "tokenomics.benefit1": "Keine Kauf-/Verkaufssteuer 🍣",
    "tokenomics.benefit2": "LP Gesperrt 🔥",
    "tokenomics.benefit3": "Keine Team-Tokens 🤝",
    "tokenomics.benefit4": "%100 Gemeinschaftsgesteuert 🌍",
    "roadmap.title": "Roadmap",
    "roadmap.subtitle": "Mit Zuversicht vorwärts gehen.",
    "roadmap.phase1": "Phase 1",
    "roadmap.phase1_title": "Start",
    "roadmap.phase1_item1": "Website-Start",
    "roadmap.phase1_item2": "Community-Setup",
    "roadmap.phase1_item3": "Marketing-Start",
    "roadmap.phase1_item4": "Fairer Start",
    "roadmap.phase2": "Phase 2",
    "roadmap.phase2_title": "Wachstum",
    "roadmap.phase2_item1": "CoinGecko-Listing",
    "roadmap.phase2_item2": "CoinMarketCap-Listing",
    "roadmap.phase2_item3": "10.000 Halter Ziel",
    "roadmap.phase2_item4": "CEX-Diskussionen",
    "roadmap.phase3": "Phase 3",
    "roadmap.phase3_title": "Dominanz",
    "roadmap.phase3_item1": "Tier-1-CEX-Listing",
    "roadmap.phase3_item2": "TUNAMI NFT-Kollektion",
    "roadmap.phase3_item3": "KI-Agent-Integration",
    "roadmap.phase3_item4": "Globales Marketing",
    "staking.title": "Stake $TUNAMI",
    "staking.subtitle": "Sperren Sie Ihre Tokens, verdienen Sie Sushi-Belohnungen.",
    "staking.apy": "Aktueller APY",
    "staking.tvl": "Gesamtwert gesperrt (TVL)",
    "staking.earned": "Verdiente Belohnungen",
    "staking.panel_title": "Staking-Panel",
    "staking.amount": "Betrag",
    "staking.balance": "Saldo",
    "staking.estimated_yield": "Geschätzter Ertrag (Jährlich)",
    "staking.lock_time": "Sperrzeit",
    "staking.stake_btn": "STAKE 🍣",
    "staking.unstake_btn": "UNSTAKE 💸",
    "staking.how_works": "Wie funktioniert es?",
    "staking.step1": "1. Wallet verbinden: Verbinden Sie Ihr Solana-Wallet (Phantom, Solflare).",
    "staking.step2": "2. Stake: Sperren Sie Ihre $TUNAMI-Tokens im Pool.",
    "staking.step3": "3. Verdienen: Verdienen Sie jede Sekunde Belohnungen.",
    "staking.vip_title": "VIP-Pools 🌊",
    "staking.vip_desc": "Bald: exklusive hochrentable Pools für NFT-Inhaber!",
    "staking.coming_soon": "Bald verfügbar",
    "footer.disclaimer": "Haftungsausschluss: Kryptowährungsinvestitionen sind mit hohem Risiko verbunden. Bitte führen Sie Ihre eigenen Recherchen durch (DYOR). Diese Website ist keine Anlageberatung.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("tr");

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
